### ISSUE TITLE
trace_span no longer compiles in 0.1.1

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tracing#151]
### Version

```
tracing: 0.1.1
```

### Description

Attempt to compile this program with `tracing = "0.1.1"` in `Cargo.toml`:
```rust
fn main() {
    tracing::trace_span!("foo");
}
```
It fails to compile on both rustc 1.35.0 and 1.36.0 with
```
error: cannot find macro `trace_span!` in this scope
 --> src/main.rs:2:5
  |
2 |     tracing::trace_span!("foo");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
It compiles fine with `tracing = "=0.1.0"`

**Comment by hawkw** [comment]
@jonhoo can you confirm that #152 fixes this for you? I can get a new point release out if it does.
