### ISSUE TITLE
`tracing` 0.1.42 breaks unqualified use of `debug` and `display` in macros

### ISSUE THREAD

**Issue by hds** [tokio-rs/tracing#3424]
## Bug Report

Up to tracing 0.1.41, this works:

```rust
    let foo = Some(42);
    let bar = true;

    tracing::info!(foo = debug(foo), bar = display(bar));
```

However, from tracing 0.1.42 (due to #3382), it fails to compile:

```
error[E0425]: cannot find function `debug` in this scope
  --> src/main.rs:12:26
   |
12 |     tracing::info!(foo = debug(foo), bar = display(bar));
   |                          ^^^^^ not found in this scope
   |
help: consider importing this function
   |
 1 + use tracing::field::debug;
   |

error[E0425]: cannot find function `display` in this scope
  --> src/main.rs:12:44
   |
12 |     tracing::info!(foo = debug(foo), bar = display(bar));
   |                                            ^^^^^^^ not found in this scope
   |
help: consider importing this function
   |
 1 + use tracing::field::display;
   |

For more information about this error, try `rustc --explain E0425`.
```

### Version

* tracing 0.1.42

### Platform

all

### Crates

* tracing

### Notes

Release train: #3413
Release PR: #3418

**Comment by hds** [comment]
I've yanked tracing 0.1.42.

Will prepare a revert tomorrow (it can't be done automatically due to other changes in the macros) and then prepare a new release.

**Comment by geofmureithi** [comment]
Some of us were too eager to update 😆

**Comment by geofmureithi** [comment]
I thing tracing-subscriber is also broken:
```
error: failed to select a version for the requirement `tracing = "^0.1.42"`
  version 0.1.42 is yanked
location searched: crates.io index
required by package `tracing-subscriber v0.3.21`
    ... which satisfies dependency `tracing-subscriber = "^0.3.21"`
```

**Comment by hds** [comment]
I still can't reproduce this issue, but obviously it's there. As such I've also yanked:
* `tracing-subscriber` 0.3.21
* `tracing-mock` 0.1.0-beta.2

**Comment by hawkw** [comment]
I would like to point out that removing the implicit imports has been proposed in the past, and we've historically chosen not to do to avoid the breaking change. The issue (#3381) that PR #3382 was intended to fix was closed when @mladedav pointed out that "fixing" it would break existing uses: https://github.com/tokio-rs/tracing/issues/3381#issuecomment-3337526569

**Comment by hds** [comment]
Yeah, that's my bad. I didn't read all the comments on the Issue closely enough, clearly.

**Comment by mladedav** [comment]
For completeness, [here](https://github.com/tokio-rs/tracing/issues/2332#issuecomment-1264521255) is even older description of this with a link to the PR 5 years ago where something like this was already merged and then reverted with more context and discussion.

**Comment by hds** [comment]
This is still our best hope: https://github.com/tokio-rs/tracing/issues/2332#issuecomment-1307329168

**Comment by hds** [comment]
Okay. So aside from the release that is mostly prepared and should make it out tomorrow, Ive been thinking about how to improve the situation we currently have with the debug and display imports and I think I’ve got something. I’ve added support for them directly into the macro rules, and that way can get rid of the imports.

It would be great if anyone who was affecting by the breaking change in tracing 0.1.42 could try tracing from this PR and see if this works for you. Obviously, I really want to hear of any cases you have where it still breaks code that worked in 0.1.41 and below.

Here's my attempt: #3426

**Comment by hds** [comment]
We've got new releases out for `tracing`, `tracing-subscriber` and `tracing-mock` (see #3413).

I'll close this issue now as the problem is resolved and this issue shouldn't be valid any more.

**Comment by tyranron** [comment]
@hds I have similar problem on 0.1.43, but with `tracing::Instrument` trait.

```
 error[E0433]: failed to resolve: could not find `tracing` in the list of imported crates
   --> api/s3/src/lib.rs:219:5
    |
219 | /     #[tracing::instrument(
220 | |        skip_all,
221 | |        fields(bucket = input.bucket.as_str(), key = input.key.as_str()),
222 | |     )]
    | |______^ could not find `tracing` in the list of imported crates
    |
    = note: this error originates in the attribute macro `tracing::instrument` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this trait
    |
  3 + use crate::tracing::Instrument;
    |
```

See [this CI job](https://github.com/instrumentisto/baza/actions/runs/19820905450/job/56782821961?pr=289) for details.

On 0.1.41 and below, it was compiling just fine.

**Comment by hds** [comment]
@tyranron This is unrelated. It is because we now (correctly) use a full path to items within the `instrument` macro rather than just `tracing`. However, if you don't actually specify the tracing crate in your Cargo.toml but have it exposed from some other crate, then this will break.

This was changed in #3126. This comment shows how you can work around this: https://github.com/tokio-rs/tracing/pull/3126#issuecomment-2955037608.

It was decided to allow this, because the alternative is that anything called `tracing` that is in scope will break the macro.

**Comment by tyranron** [comment]
@hds okay, thanks for the explanation. Just didn't expect such a change to slip in a patch release.

**Comment by hds** [comment]
We don't really have patch releases, this is a "minor" release because tracing is 0.1. All releases are minor because we don't have a place for a patch version.

I understand your concern, but this is a question of macro higiene and it was going to be broken one way or another. It's better if it's "broken" in the predicable way.

**Comment by tyranron** [comment]
@hds this is not a concern, just a note. I do understand that before 1.0 everything could be broken at any time. But it's also easy to get used to this not happening most of the time. Nothing to blame `tracing` team about here.

**Comment by hds** [comment]
@tyranron We **don't** generally admit any breaking changes pre-1.0 except when moving between 0.x - 0.y versions. As per Cargo (Rust) semver, this is a major change and breaks are allowed.

This case you're describing was special in that we were fixing obviously incorrect behaviour and while we were aware that there were some cases where it would break users, it was decided that the fix was worth it. I'm sorry that we broke your code, as I said, we really do try to avoid doing that and you should generally be able to expect no breaks unless we bump the pre-1.0 major version (i.e. 0.x - 0.y).

My comment above was only that 0.1.a - 0.1.b change should be considered a "minor" version change, not a "patch" version change. I didn't want to imply that we will release breaking changes in either, we do our best not to wherever possible.
